# 1 
  I believe that deep neural networks really are a breakthrough which will be used for years in the future. Just look at how they have been used already. In 1996 Deep Blue beat Garry Kasparov who to this day is one of the world's greatest chess players. The modern iteration of which is AlphaZero which has mastered both Chess and Go at a whole different level. Besides board games, neural networks can be trained to read images and classify different people. Apple phones create albums in which a certain persons face appears. People use these networks for convenience and research. 

  In a more technical light. We can see why these deep neural networks are here to stay more than the old perceptrons or expert systems in that the new deep neural networks can be built with self learning. Modern systems such as LSTM or algorithms like the Monte Carlo enable the model to improve upon each training iteration. Unlike the old models which couldn't do this to the same extent. 

  # 2

In [2]:
import numpy as np

print("Initial Weights:")
xorInput = np.array([1, 1])
layerOneWeights = np.array([[0.11, 0.12], [0.21, 0.08]])
layerTwoWeights = np.array([[0.14], [0.15]])

print("xor input ", xorInput)
print("layer 1 weights \n", layerOneWeights)
print("layer 2 weights \n", layerTwoWeights, "\n")

print("Output:")
product1 = xorInput.dot(layerOneWeights)
oj = product1.dot(layerTwoWeights)
print("forward pass result = ", oj, "\n")

print("Error:")
l2error = (0 - oj[0])**2
print("L2Error = ", l2error)
delta = (0 - oj[0])
print("Delta = ", delta, "\n")

print("Back Propogate Updates: ")
learningRate = 0.05
print("learning rate = ", learningRate)
newLayerTwoWeights = np.add(layerTwoWeights, learningRate * product1.reshape(2,1) * 1.0 * delta)
print("updated layer two weights \n", newLayerTwoWeights)
newLayerOneWeights = np.add(layerOneWeights, learningRate * delta * np.array([[1], [1]]).dot(layerTwoWeights.reshape(1,2)))
print("updated layer one weights \n", newLayerOneWeights)

Initial Weights:
xor input  [1 1]
layer 1 weights 
 [[0.11 0.12]
 [0.21 0.08]]
layer 2 weights 
 [[0.14]
 [0.15]] 

Output:
forward pass result =  [0.0748] 

Error:
L2Error =  0.005595040000000001
Delta =  -0.0748 

Back Propogate Updates: 
learning rate =  0.05
updated layer two weights 
 [[0.1388032]
 [0.149252 ]]
updated layer one weights 
 [[0.1094764 0.119439 ]
 [0.2094764 0.079439 ]]


# 3

In [12]:
from keras import layers
from keras import models

model = models.Sequential()

# Configure a convnet with 3 layers of convolutions and max pooling.
model.add(layers.Conv2D(64, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(32, (3, 3), activation='relu'))

# Add layers to flatten the 2D image and then do a 10-way classification.
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.summary()

from keras.datasets import fashion_mnist
from keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

train_images = train_images.reshape((60000, 28, 28, 1))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32') / 255

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=5, batch_size=64)
model.evaluate(test_images, test_labels)

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_26 (Conv2D)           (None, 26, 26, 64)        640       
_________________________________________________________________
max_pooling2d_18 (MaxPooling (None, 13, 13, 64)        0         
_________________________________________________________________
conv2d_27 (Conv2D)           (None, 11, 11, 64)        36928     
_________________________________________________________________
max_pooling2d_19 (MaxPooling (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_28 (Conv2D)           (None, 3, 3, 32)          18464     
_________________________________________________________________
flatten_8 (Flatten)          (None, 288)               0         
_________________________________________________________________
dense_15 (Dense)             (None, 64)               

[0.314449747633934, 0.8895999789237976]

In summary, I used the cnn example from the cs344-code repo. I used the fashion_mnist dataset instead of the mnist dataset, and then messed around with tweaking the number of layers as well as the nodes within those layers. I came to the conclusion that 3 layers worked best with the node counts seen in the code above. The accuracy was highest at 91.132. This number is not the best as a performance measurement, but it is the highest I could achieve with this cnn layout.